{
 "title": "Response Times",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Code 200",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(response_times_bucket{ResponseCode=\"200\", Error=\"false\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distribution Response Code 200",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "response_times_bucket{ResponseCode=\"200\", Error=\"false\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distribution Response Code Non-200",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "response_times_bucket{ResponseCode!=\"200\", Error=\"false\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Code Non-200",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(response_times_bucket{ResponseCode!=\"200\", Error=\"false\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distribution Error",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "response_times_bucket{Error=\"true\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Code Error",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(response_times_bucket{Error=\"true\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}