version: '3.7'
services:
  networkmonitor:
    build: src/.
    container_name: networkmonitor
    ports:
      - "5600:5600"
    environment: 
      BASE_URL : ":5600"
      TARGET_ADDR : "http://host.docker.internal:8080"
      SLEEP_DURATION : 1
    networks:
      - networkmonitor-network      
  prometheus:
    build: prometheus/.
    container_name: networkmonitor_prometheus
    networks:
      - networkmonitor-network    
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on: 
      - prometheus  
    networks:
      - networkmonitor-network      
networks:
  networkmonitor-network:    
volumes:
  grafana-storage: